name: ekokai-api
services:
- name: ekokai-backend
  source_dir: /
  github:
    repo: tu-usuario/ekokai
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  # Base de datos MongoDB
  - key: MONGO_URI_DB1
    value: mongodb+srv://kamilaopazo1:206000643@clustertrabajo.hyiima4.mongodb.net/ekokai?retryWrites=true&w=majority&appName=ClusterTrabajo
  # JWT Secret
  - key: JWT_SECRET
    value: supersecreto123
  # Twilio Live Credentials
  - key: TWILIO_ACCOUNT_SID
    value: AC1be585d06467e3e11576154ba13889d7
  - key: TWILIO_AUTH_TOKEN
    value: 1751b5029f7c8b68e72a9b601696d658
  - key: TWILIO_WHATSAPP_NUMBER
    value: whatsapp:+14155238886
  # Google Cloud / Dialogflow Credentials
  - key: DIALOGFLOW_PROJECT_ID
    value: ekokai-chat-sxgd
  - key: GC_TYPE
    value: service_account
  - key: GC_PROJECT_ID
    value: ekokai-chat-sxgd
  - key: GC_PRIVATE_KEY_ID
    value: eb5ca2bd9e90972999c519573db1bc887ff79211
  - key: GC_PRIVATE_KEY
    value: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDv/0CyZV2ozz1e\nDc3THnJoOBIc4HVOFdaaT2MPGGOH3q+hNomJO7wdfoqBqNTw5WC9tAoug1FJ7WL0\n1bm88rmzq8ECBYw3T5YXxa5Ds16SLM1Jtw2Ne1BxPAEu5s7nBMczsRZtD4LTSYr/\n1xEdpLStsOWTeMspkxsZ5Ve1Etl46whUaltJ5uN+uCEXjqjziDRo8tRWD1vv02d/\n8+ztWqvhI2ZF4vLJY/0v8+DeWcCj0ld+HGwPVs1lhYCbSDTY65KyzXhRLdynAoIQ\nFX8z8/Ixe14B1dKpdAIlmIHKvBKkHlflsqC/9XPN9jRMQisIC2RB2oxL6/aBm/vb\n/P0QbVDfAgMBAAECggEATzUZp6cPxb57/PYmV4alcKMMy04DOR25AZ2wzlMYykdj\nBJxowQufdsaENO3BNa4mgwWQFLDPW8xGjBKbpfIf+t31KdMl5z1Tho3+CScCT9EM\ngccx6F9p+a05oL6ZS6KGkhdglOb5IP2VLAHRisyIuwh2hHjp6FM+LwpDq6XIc4DO\n1j1ajFgAYl8JCyOel7BB0bkxvpRnEf6yCgW/T0LV28+TuoCj1qdAqwBxZugNNAZV\nIyC9lcGJ7SEakxmLiuldnVxZ5dUrcvNEfbky3Gm/bOK41w2M59Y+e7OfZWiwwpVm\n6KkzzoCn3GOqkNzLmM50lvd96PfXmCIVJU0RqPSdYQKBgQD4hH2QUmm0yCzH1coh\nn9wTW3uDqtQUmAGE93lkA+itTeBk4GcxmFZccT/Cg2PxrkI5lepsC3sxNOyrLHDA\nYLPOMasKjS7qcibKNPQ9/EZdoeHQ20QZgjMNXB+2mk0gaU31enaa9gSsPESPAvgF\nJucSRQWd52yNYEY9uZWA5oh54QKBgQD3ORa2ILA9KntUfzRuq2Hs2HpAMLr+7XeX\nDGbZH0vDhPQB+DG5bIbHtf9DteTye68+JdxWNWB8uoSWHBE8L30WwoDeWzg7wggj\nYiAhHicxpIF8m2aNlmahnka4v7KLMmQYCu0Ywk6VvYbuYhZI0rgvSs9q0NIirbdG\n/egG5rqivwKBgCz+B6GOWhbhusG/IeYug/B5OoZe8iB8WKITD8Ycsw5VMA/zVJt1\nAgWgdzOnB/wkWVcFnjhLZ9VDyKlA1XTuzP7CnT2+y8SkQAORzLpAJxkiirh+Sfj4\nSnfbut4bV2VLy1JrBngNnFD2ZE8j8XU1UtZK6rZoxI1f5bedFsUMd57hAoGBAMMY\nFCop5ap/SdBGihQDv0VvGBpr2kWvFD7pFIinP9zNoNmlCWhwknQr1YOTmVcZ8BM1\nQYnumXQUpOjowVkjiK1bVOMkTV4rIsz5dK1t5DQyw9SXtfhqBhfolZrZ/IYIgCDR\nDoYJYIaeiEq6sSdK0vrPKJv8qrefKxEk8ePwVLx1AoGBAL8RLr8RZabC7FjiWoP1\nFA/g85vN7b7aXflAJ2PlUAXworYuhKEnTpwzzM/ME8tMtTULlzj5c9Hl0Djl09Df\nXW2Lky8+2IFO1AdfwppSctCXaPID30s8sr6PzlZXdats+LhIYEwXRdo1GrQRJ5p3\nLeW38n/JA+Zw/Dw3EiF8SITl\n-----END PRIVATE KEY-----\n"
  - key: GC_CLIENT_EMAIL
    value: ekokai-chat@ekokai-chat-sxgd.iam.gserviceaccount.com
  - key: GC_CLIENT_ID
    value: "110418399146269369162"
  - key: GC_AUTH_URI
    value: https://accounts.google.com/o/oauth2/auth
  - key: GC_TOKEN_URI
    value: https://oauth2.googleapis.com/token
  - key: GC_AUTH_PROVIDER_X509_CERT_URL
    value: https://www.googleapis.com/oauth2/v1/certs
  - key: GC_CLIENT_X509_CERT_URL
    value: https://www.googleapis.com/robot/v1/metadata/x509/ekokai-chat%40ekokai-chat-sxgd.iam.gserviceaccount.com
  - key: GC_UNIVERSE_DOMAIN
    value: googleapis.com 